export const CALABAR_LOCATIONS = [
  "Marian",
  "Satellite Town",
  "State Housing Estate",
  "Federal Housing Estate",
  "Ekorinim",
  "8 Miles",
  "7 Miles",
  "Parliamentary Road & Extension",
  "Eta Agbor",
  "Atekong",
  "Asari Eso",
  "Ikot Ansa",
  "Ikot Ishie",
  "Ikot Omin",
  "Ikot Effanga",
  "Ikot Nkebre",
  "Diamond Hill",
  "MCC Road Area",
  "Calabar Harbour / Free Trade Zone",
  "Calabar South",
  "Duke Town",
  "Henshaw Town",
  "Anantigha",
  "Ekpo Abasi",
  "Uwanse",
  "Mbukpa",
  "Edibedibe",
  "Goldie",
  "Target",
  "Nelson Mandela",
  "Boco Street Area",
  "Afokang",
  "Jebs",
] as const;
